import type { GovernmentProgram } from './types';

export const PROGRAMS: GovernmentProgram[] = [

  // ============================================================
  // 🌐 DIGITAL NOMAD VISAS
  // ============================================================
  {
    id: 'ee-digital-nomad-visa',
    name: 'Digital Nomad Visa',
    institution: 'Estonian Police and Border Guard Board',
    country: 'EE',
    flag: '🇪🇪',
    type: 'digital_nomad_visa',
    audience: ['digital_nomad', 'freelancer'],
    description:
      'Estonia was the first country in the world to introduce a Digital Nomad Visa in 2020. Remote workers earning at least €3,504/month can legally live and work in Estonia for up to 1 year.',
    termMaxMonths: 12,
    features: [
      'Up to 12 months stay',
      'Access to Schengen Area',
      'Can open EU bank account',
      'Access to e-services',
      'Eligible for e-Residency application',
      'Valid for employees and freelancers',
    ],
    requirements: [
      'Monthly income ≥ €3,504',
      'Work for foreign company or own foreign company',
      'Valid health insurance',
      'Proof of accommodation',
    ],
    link: 'https://www.politsei.ee/en/instructions/digital-nomad-visa',
    isDigitalNomadFriendly: true,
    tags: ['visa', 'digital nomad', 'remote work'],
  },
  {
    id: 'lv-digital-nomad-visa',
    name: 'Digital Nomad Visa',
    institution: 'Office of Citizenship and Migration Affairs of Latvia',
    country: 'LV',
    flag: '🇱🇻',
    type: 'digital_nomad_visa',
    audience: ['digital_nomad', 'freelancer'],
    description:
      'Latvia introduced the Digital Nomad Visa in 2021 for non-EU citizens working remotely. Stay in Riga for up to 1 year with access to Schengen Area.',
    termMaxMonths: 12,
    features: [
      'Up to 12 months (renewable)',
      'Schengen access',
      'Affordable cost of living',
      'Fast-growing tech hub (Riga)',
      'EU banking access',
    ],
    requirements: [
      'Monthly income ≥ €2,857',
      'Remote work proof',
      'Health insurance',
      'Accommodation proof',
    ],
    link: 'https://www.pmlp.gov.lv/en/digital-nomad-visa',
    isDigitalNomadFriendly: true,
    tags: ['visa', 'digital nomad', 'riga'],
  },
  {
    id: 'lt-freelance-visa',
    name: 'Freelancer / Startup Visa',
    institution: 'Migration Department of Lithuania',
    country: 'LT',
    flag: '🇱🇹',
    type: 'startup_visa',
    audience: ['digital_nomad', 'startup', 'freelancer'],
    description:
      'Lithuania offers a Startup Visa for entrepreneurs and a freelancer-friendly temporary residence permit. Vilnius has a growing tech ecosystem with low taxes and EU access.',
    termMaxMonths: 36,
    features: [
      'Startup Visa: 3-year residence',
      'Access to Startup Lithuania network',
      'EU banking & payments',
      'Low corporate tax (15%)',
      'Revolut Bank licensed in Lithuania',
    ],
    requirements: [
      'Viable startup business plan',
      'Minimum capital €2,500',
      'Or: freelance income proof',
    ],
    link: 'https://startuplithuania.com/startup-visa/',
    isDigitalNomadFriendly: true,
    tags: ['visa', 'startup', 'freelancer', 'vilnius'],
  },
  {
    id: 'no-svalbard-nomad',
    name: 'Svalbard Visa-Free Access',
    institution: 'Governor of Svalbard (Sysselmannen)',
    country: 'NO',
    flag: '🇳🇴',
    type: 'digital_nomad_visa',
    audience: ['digital_nomad', 'freelancer'],
    description:
      'Svalbard (Norway) is visa-free for all nationalities under the Svalbard Treaty. Remote workers can stay indefinitely — unique in Europe. Note: no ferry to mainland Norway without Schengen.',
    features: [
      'Visa-free for all nationalities',
      'No time limit on stay',
      'Arctic experience',
      'Norwegian internet infrastructure',
      'Remote and unique working environment',
    ],
    requirements: [
      'Proof of self-sufficiency (income/savings)',
      'Health insurance',
      'Accommodation in Longyearbyen',
    ],
    link: 'https://www.sysselmannen.no/en/',
    isDigitalNomadFriendly: true,
    tags: ['visa-free', 'arctic', 'unique'],
  },
  {
    id: 'is-longterm-visa',
    name: 'Long-Term Visa (Type D)',
    institution: 'Útlendingastofnun (Directorate of Immigration)',
    country: 'IS',
    flag: '🇮🇸',
    type: 'digital_nomad_visa',
    audience: ['digital_nomad', 'freelancer'],
    description:
      'Iceland offers a 6-month long-term visa for remote workers. Though not branded as a "digital nomad visa", it permits extended stays for location-independent workers.',
    termMaxMonths: 6,
    features: [
      'Up to 6 months',
      'Stunning nature environment',
      'Fast broadband infrastructure',
      'High standard of living',
      'EEA member (not EU)',
    ],
    requirements: [
      'Minimum income: ISK 1,000,000/month (~€7,000)',
      'Proof of remote employment',
      'Health insurance',
    ],
    link: 'https://utl.is/index.php/en/',
    isDigitalNomadFriendly: true,
    tags: ['visa', 'iceland', 'remote work'],
  },

  // ============================================================
  // 🇪🇪 e-RESIDENCY PROGRAMS
  // ============================================================
  {
    id: 'ee-e-residency',
    name: 'e-Residency Program',
    institution: 'Enterprise Estonia (EAS)',
    country: 'EE',
    flag: '🇪🇪',
    type: 'e_residency',
    audience: ['e_resident', 'startup', 'freelancer', 'digital_nomad'],
    description:
      "Estonia's e-Residency is a transnational digital identity that allows anyone in the world to establish and run an EU-based company online. Over 100,000 e-residents from 170+ countries have used it.",
    features: [
      'Digital EU company registration in minutes',
      'Sign documents digitally anywhere',
      'Access to EU banking (LHV, Wise Business)',
      'EU VAT registration',
      'Transparent 20% corporate tax on profit distribution',
      'Full access to Estonian e-services',
      'Fintech-friendly ecosystem',
    ],
    requirements: [
      'Application fee: €120–170',
      'Background check',
      'No criminal record',
      'Pick up kit at Estonian embassy',
    ],
    link: 'https://e-resident.gov.ee/',
    isEResidentFriendly: true,
    isDigitalNomadFriendly: true,
    tags: ['e-residency', 'EU company', 'digital identity'],
  },
  {
    id: 'lhv-e-resident-banking',
    name: 'e-Resident Business Banking',
    institution: 'LHV Pank',
    country: 'EE',
    flag: '🇪🇪',
    type: 'e_residency',
    audience: ['e_resident', 'startup', 'digital_nomad'],
    description:
      'LHV Pank is the go-to bank for Estonian e-residents. Open a fully functional EU business bank account remotely using your e-Residency card. Supports SEPA, SWIFT, and multi-currency.',
    features: [
      'Remote account opening with e-Residency card',
      'SEPA & SWIFT transfers',
      'Business debit card (Mastercard)',
      'Online banking 24/7',
      'API banking for fintechs',
      'Multi-currency support',
      'Integration with Xero/accounting tools',
    ],
    requirements: [
      'Valid Estonian e-Residency card',
      'Registered Estonian OÜ company',
      'Business activity verification',
    ],
    link: 'https://www.lhv.ee/en/business',
    isEResidentFriendly: true,
    isDigitalNomadFriendly: true,
    tags: ['banking', 'e-residency', 'business account'],
  },
  {
    id: 'wise-business-nordics',
    name: 'Wise Business Multi-Currency Account',
    institution: 'Wise (formerly TransferWise)',
    country: 'EE',
    flag: '🌐',
    type: 'e_residency',
    audience: ['digital_nomad', 'e_resident', 'startup', 'freelancer'],
    description:
      'Wise Business (EU-licensed, EE branch) offers multi-currency accounts ideal for digital nomads and e-residents in Nordic & Baltic countries. Hold DKK, SEK, NOK, EUR, GBP and 50+ currencies.',
    features: [
      'Hold 50+ currencies',
      'Local account details in EUR, GBP, USD',
      'Real exchange rate (no markup)',
      'Debit card for global spending',
      'API integration',
      'Invoicing tools',
    ],
    requirements: [
      'Business registration in EU/EEA',
      'Identity verification',
    ],
    link: 'https://wise.com/eu/business/',
    isDigitalNomadFriendly: true,
    isEResidentFriendly: true,
    tags: ['fintech', 'multi-currency', 'banking'],
  },
  {
    id: 'revolut-business-lt',
    name: 'Revolut Business (EU Banking)',
    institution: 'Revolut Bank UAB',
    country: 'LT',
    flag: '🇱🇹',
    type: 'e_residency',
    audience: ['digital_nomad', 'startup', 'sme', 'e_resident'],
    description:
      'Revolut Bank is licensed in Lithuania and serves the entire EU. Business accounts for startups, SMEs and nomads with powerful financial tools. Hold and exchange 25+ currencies instantly.',
    features: [
      'Lithuanian banking license (EU-regulated)',
      'Instant EUR/currency exchange',
      'Business debit/credit cards',
      'Payroll & expense management',
      'API access',
      '25+ currencies',
      'Free tier available',
    ],
    requirements: [
      'EU/EEA registered company',
      'Identity verification',
      'Business verification',
    ],
    link: 'https://www.revolut.com/business/',
    isDigitalNomadFriendly: true,
    isEResidentFriendly: true,
    tags: ['fintech', 'digital banking', 'startup-friendly'],
  },
  {
    id: 'paysera-baltic',
    name: 'Paysera Business Account',
    institution: 'Paysera LT',
    country: 'LT',
    flag: '🇱🇹',
    type: 'e_residency',
    audience: ['sme', 'startup', 'e_resident', 'freelancer'],
    description:
      'Paysera is a Lithuanian fintech licensed as an Electronic Money Institution in the EU. Very popular in Baltic countries for affordable SEPA payments and business accounts.',
    features: [
      'Free account opening',
      'SEPA & SWIFT transfers',
      'Mass payouts',
      'Payment gateway integration',
      'Lowest fees in Baltics',
      '30+ currencies',
    ],
    requirements: [
      'EU/EEA company or individual',
      'Identity & business verification',
    ],
    link: 'https://www.paysera.com/v2/en-GB/business',
    isEResidentFriendly: true,
    tags: ['fintech', 'payments', 'low-cost'],
  },

  // ============================================================
  // 🚀 STARTUP & ENTREPRENEUR SUPPORT
  // ============================================================
  {
    id: 'ee-kredex-startup',
    name: 'KredEx Startup Loan',
    institution: 'KredEx (Enterprise Estonia Group)',
    country: 'EE',
    flag: '🇪🇪',
    type: 'startup_loan',
    audience: ['startup', 'sme'],
    description:
      'KredEx provides startup loans and credit guarantees to Estonian companies and e-Residency companies. Startup loans up to €300,000 with favorable terms for early-stage businesses.',
    maxAmount: 300000,
    currency: 'EUR',
    rateMin: 4.5,
    rateMax: 9.0,
    termMaxMonths: 60,
    features: [
      'Loan up to €300K',
      'Startup-friendly collateral',
      'Mentoring & advisory support',
      'Open to e-resident companies',
      'Fast application process',
    ],
    requirements: [
      'Registered in Estonia (incl. e-resident OÜ)',
      'Viable business plan',
      'Less than 3 years old (startup)',
    ],
    link: 'https://kredex.ee/en/business/startup-loan/',
    isEResidentFriendly: true,
    tags: ['startup', 'loan', 'estonia'],
  },
  {
    id: 'ee-eas-startup',
    name: 'EAS Startup Grant',
    institution: 'Enterprise Estonia (EAS)',
    country: 'EE',
    flag: '🇪🇪',
    type: 'grant',
    audience: ['startup', 'innovator'],
    description:
      'Enterprise Estonia (EAS) provides grants, advisory services, and support programs for Estonian startups. The Startup Estonia program is a government initiative to make Estonia the best place to start a company.',
    maxAmount: 200000,
    currency: 'EUR',
    features: [
      'Non-repayable grants',
      'R&D co-financing',
      'Startup Visa support',
      'International market access',
      'Investor network access',
    ],
    requirements: [
      'Estonian company',
      'Innovative product/service',
      'Growth ambitions',
    ],
    link: 'https://startupestonia.ee/',
    tags: ['grant', 'startup', 'innovation'],
  },
  {
    id: 'lv-altum-microloan',
    name: 'ALTUM Micro Loan',
    institution: 'ALTUM (State Development Finance Institution)',
    country: 'LV',
    flag: '🇱🇻',
    type: 'microloan',
    audience: ['startup', 'sme', 'individual'],
    description:
      "ALTUM is Latvia's state development finance institution. The microloan program supports small businesses and startups with loans up to €25,000 at preferential rates — no collateral required for small amounts.",
    maxAmount: 25000,
    currency: 'EUR',
    rateMin: 3.0,
    rateMax: 7.0,
    termMaxMonths: 60,
    features: [
      'No collateral for loans ≤ €5,000',
      'Available throughout Latvia',
      'Business advisory support',
      'EU co-financed',
      'Accessible to rural businesses',
    ],
    requirements: [
      'Registered in Latvia',
      'Operational ≤ 5 years',
      'Business plan required',
    ],
    link: 'https://www.altum.lv/en/services/loans/',
    tags: ['microloan', 'startup', 'latvia'],
  },
  {
    id: 'lv-altum-startup',
    name: 'ALTUM Startup Loan',
    institution: 'ALTUM (State Development Finance Institution)',
    country: 'LV',
    flag: '🇱🇻',
    type: 'startup_loan',
    audience: ['startup', 'sme'],
    description:
      "ALTUM's startup loan program targets innovative Latvian startups with loans up to €200,000. Combined with guarantee programs to help young companies access commercial bank credit.",
    maxAmount: 200000,
    currency: 'EUR',
    rateMin: 4.0,
    rateMax: 8.5,
    termMaxMonths: 72,
    features: [
      'Loans up to €200K',
      'Loan guarantees available',
      'Export financing support',
      'Green investment bonus',
    ],
    requirements: [
      'Latvian registered company',
      'Innovative activity',
      'Less than 5 years operating',
    ],
    link: 'https://www.altum.lv/en/services/loans/startup-loan/',
    tags: ['startup', 'loan', 'latvia'],
  },
  {
    id: 'lt-invega-guarantee',
    name: 'Invega Loan Guarantee',
    institution: 'Invega (Investment and Business Guarantees)',
    country: 'LT',
    flag: '🇱🇹',
    type: 'guarantee',
    audience: ['startup', 'sme', 'corporate'],
    description:
      'Invega provides state guarantees for bank loans in Lithuania, enabling SMEs and startups to access credit they would not otherwise qualify for. Covers up to 80% of the loan amount.',
    maxAmount: 5000000,
    currency: 'EUR',
    features: [
      'Guarantee up to 80% of loan value',
      'Works with all major Lithuanian banks',
      'Startup & SME focused',
      'EU-funded programs available',
      'Agricultural & innovation support',
    ],
    requirements: [
      'Lithuanian company',
      'Commercial bank loan application',
      'Viable business plan',
    ],
    link: 'https://www.invega.lt/en/',
    tags: ['guarantee', 'sme', 'lithuania'],
  },
  {
    id: 'fi-finnvera-sme',
    name: 'Finnvera SME Loan',
    institution: 'Finnvera (State-Owned Specialised Financing Company)',
    country: 'FI',
    flag: '🇫🇮',
    type: 'government_loan',
    audience: ['sme', 'startup', 'corporate'],
    description:
      "Finnvera is Finland's official export credit agency and SME financier. SME loans up to €1M with state-backed guarantees, particularly useful for small companies without significant collateral.",
    maxAmount: 1000000,
    currency: 'EUR',
    rateMin: 3.5,
    rateMax: 8.0,
    termMaxMonths: 120,
    features: [
      'Loans up to €1M',
      'State-backed guarantee',
      'Export credit available',
      'Startup loan for new entrepreneurs',
      'Green transition financing',
    ],
    requirements: [
      'Finnish company or new entrepreneur',
      'Business plan',
      'Viable repayment capacity',
    ],
    link: 'https://www.finnvera.fi/eng/sme-finance',
    tags: ['sme', 'loan', 'finland', 'export'],
  },
  {
    id: 'fi-business-finland',
    name: 'Business Finland Innovation Funding',
    institution: 'Business Finland',
    country: 'FI',
    flag: '🇫🇮',
    type: 'innovation_fund',
    audience: ['startup', 'innovator', 'sme'],
    description:
      'Business Finland provides grants and loans for R&D and innovation projects. Startup grants, market access funding, and innovation loans for Finnish companies aiming for international growth.',
    maxAmount: 500000,
    currency: 'EUR',
    rateMin: 1.0,
    rateMax: 3.0,
    features: [
      'R&D grants (non-repayable part)',
      'Innovation loans at low rates',
      'Market access funding',
      'Internationalisation support',
      'Young Innovative Company program',
    ],
    requirements: [
      'Finnish-registered company',
      'Innovative product/service',
      'International growth potential',
    ],
    link: 'https://www.businessfinland.fi/en/for-finnish-customers/services/funding',
    tags: ['grant', 'innovation', 'R&D', 'startup'],
  },
  {
    id: 'no-innovasjon-norge',
    name: 'Innovation Norway Basic Loan',
    institution: 'Innovasjon Norge',
    country: 'NO',
    flag: '🇳🇴',
    type: 'government_loan',
    audience: ['startup', 'sme', 'innovator'],
    description:
      'Innovation Norway (Innovasjon Norge) offers basic loans to Norwegian startups and SMEs at preferential rates. Loans from NOK 500,000 to NOK 3M for companies with significant growth potential.',
    maxAmount: 3000000,
    currency: 'NOK',
    rateMin: 5.0,
    rateMax: 9.0,
    termMaxMonths: 84,
    features: [
      'Loans from NOK 500K to 3M',
      'Startup & innovation focus',
      'Flexible repayment',
      'Mentoring and advisory',
      'International market access',
      'Green economy priority',
    ],
    requirements: [
      'Norwegian company',
      'Growth ambition',
      'Innovation element',
      'Viable business plan',
    ],
    link: 'https://www.innovasjonnorge.no/en/start-page/our-services/loans/',
    tags: ['startup', 'loan', 'norway', 'innovation'],
  },
  {
    id: 'se-almi-loan',
    name: 'Almi Business Loan',
    institution: 'Almi Företagspartner AB',
    country: 'SE',
    flag: '🇸🇪',
    type: 'government_loan',
    audience: ['startup', 'sme', 'corporate'],
    description:
      "Almi is Sweden's government-owned business lender, providing loans where commercial banks cannot. Business loans from SEK 100,000 to SEK 10M for startups and growing SMEs.",
    maxAmount: 10000000,
    currency: 'SEK',
    rateMin: 6.0,
    rateMax: 11.0,
    termMaxMonths: 72,
    features: [
      'Loans from SEK 100K to 10M',
      'No collateral required for small loans',
      'Startup loan (Startlån) program',
      'Business advisory included',
      'Regional offices nationwide',
    ],
    requirements: [
      'Swedish company',
      'Viable business plan',
      'Cannot get full commercial bank loan',
    ],
    link: 'https://www.almi.se/en/financing/',
    tags: ['sme', 'startup', 'sweden', 'government'],
  },
  {
    id: 'dk-vaekstfonden',
    name: 'Vækstfonden Growth Loan',
    institution: 'Vækstfonden (Danish Growth Fund)',
    country: 'DK',
    flag: '🇩🇰',
    type: 'government_loan',
    audience: ['startup', 'sme', 'innovator'],
    description:
      "Vækstfonden is Denmark's state investment fund providing loans, guarantees, and venture capital to Danish startups and SMEs. Growth loans from DKK 500K to DKK 10M.",
    maxAmount: 10000000,
    currency: 'DKK',
    rateMin: 6.0,
    rateMax: 12.0,
    termMaxMonths: 84,
    features: [
      'Growth loans & venture capital',
      'Loan guarantees for bank financing',
      'Startup financing',
      'Green transition focus',
      'Digital and tech sector priority',
    ],
    requirements: [
      'Danish company',
      'Growth potential',
      'Minimum 2 years operating (for growth loan)',
      'OR early-stage startup with innovation',
    ],
    link: 'https://www.vf.dk/en/',
    tags: ['startup', 'growth', 'denmark', 'venture'],
  },
  {
    id: 'is-byggdastofnun',
    name: 'Regional Development Loan',
    institution: 'Byggðastofnun (Regional Development Institute)',
    country: 'IS',
    flag: '🇮🇸',
    type: 'government_loan',
    audience: ['sme', 'startup', 'corporate'],
    description:
      'Byggðastofnun provides subsidized loans for businesses outside Reykjavik metropolitan area, supporting regional development and job creation in rural Iceland.',
    maxAmount: 150000000,
    currency: 'ISK',
    rateMin: 7.0,
    rateMax: 11.0,
    termMaxMonths: 120,
    features: [
      'Regional Iceland focus',
      'Job creation priority',
      'Tourism & fisheries eligible',
      'Below-market interest rates',
      'Long repayment terms',
    ],
    requirements: [
      'Icelandic company outside Reykjavik',
      'Regional job creation',
      'Business plan required',
    ],
    link: 'https://www.byggdastofnun.is/en',
    tags: ['regional', 'iceland', 'rural'],
  },

  // ============================================================
  // 🇪🇺 EU FUNDING PROGRAMS
  // ============================================================
  {
    id: 'eu-eib-sme',
    name: 'EIB SME Finance (via local banks)',
    institution: 'European Investment Bank (EIB)',
    country: 'EU',
    flag: '🇪🇺',
    type: 'eu_fund',
    audience: ['sme', 'startup', 'corporate'],
    description:
      'The EIB provides funding to SMEs in Nordic & Baltic countries through local partner banks (Nordea, SEB, Swedbank, etc.) at below-market rates. Loans from €25K to €12.5M.',
    maxAmount: 12500000,
    currency: 'EUR',
    rateMin: 2.5,
    rateMax: 6.0,
    termMaxMonths: 120,
    features: [
      'Below-market interest rates',
      'Available in all 8 countries',
      'Via local partner banks',
      'Up to €12.5M per beneficiary',
      'Green investment priority',
      'Innovation & digitalisation',
    ],
    requirements: [
      'SME with <250 employees',
      'Turnover <€50M or balance sheet <€43M',
      'Apply via local partner bank',
    ],
    link: 'https://www.eib.org/en/products/loans/sme/index.htm',
    tags: ['EU', 'SME', 'low-rate', 'green'],
  },
  {
    id: 'eu-eif-guarantee',
    name: 'EIF SME Guarantee Facility',
    institution: 'European Investment Fund (EIF)',
    country: 'EU',
    flag: '🇪🇺',
    type: 'guarantee',
    audience: ['sme', 'startup', 'innovator'],
    description:
      'The EIF provides guarantees to banks lending to SMEs, enabling businesses to access credit at better terms. Works through local banks in all Nordic & Baltic EU member states.',
    features: [
      'Reduces bank collateral requirements',
      'Works in EU member states (DK, FI, SE, EE, LV, LT)',
      'Startup and micro-enterprise friendly',
      'Social enterprise support',
      'Digital economy companies',
    ],
    requirements: [
      'SME registered in EU member state',
      'Apply via local participating bank',
      'Specific programs vary by country',
    ],
    link: 'https://www.eif.org/what_we_do/guarantees/',
    tags: ['EU', 'guarantee', 'SME'],
  },
  {
    id: 'eu-horizon-europe',
    name: 'Horizon Europe R&D Funding',
    institution: 'European Commission',
    country: 'EU',
    flag: '🇪🇺',
    type: 'innovation_fund',
    audience: ['startup', 'innovator', 'corporate', 'sme'],
    description:
      "Horizon Europe is the EU's flagship R&D program with €95.5B budget for 2021–2027. All 8 Nordic & Baltic countries participate. EIC Accelerator for startups: grants up to €2.5M + €15M equity.",
    maxAmount: 2500000,
    currency: 'EUR',
    features: [
      'EIC Accelerator: up to €2.5M grant',
      'EIC Equity: up to €15M investment',
      'All 8 NB countries eligible',
      'Climate, health, digital themes',
      'Collaborative research projects',
    ],
    requirements: [
      'Breakthrough innovation',
      'EU/EEA company',
      'Demonstrated technical readiness (TRL 5+)',
      'Strong team & business plan',
    ],
    link: 'https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en',
    tags: ['EU', 'R&D', 'deep tech', 'grant'],
  },
  {
    id: 'eu-investeu',
    name: 'InvestEU Programme',
    institution: 'European Commission / EIB Group',
    country: 'EU',
    flag: '🇪🇺',
    type: 'eu_fund',
    audience: ['corporate', 'sme', 'innovator'],
    description:
      'InvestEU mobilises public and private investment across the EU. The programme focuses on sustainable infrastructure, innovation, digital economy, and social investment in all 8 NB countries.',
    maxAmount: 50000000,
    currency: 'EUR',
    features: [
      'Large-scale infrastructure',
      'Digital transition investment',
      'Green Deal alignment',
      'Social and skills investment',
      'SME and midcap access',
    ],
    requirements: [
      'Project in EU member state',
      'Minimum investment of €7.5M',
      'Via EIB or national promotional banks',
    ],
    link: 'https://investeu.europa.eu/index_en',
    tags: ['EU', 'infrastructure', 'digital', 'green'],
  },
  {
    id: 'eu-easi-social',
    name: 'EaSI – Social Entrepreneurship Finance',
    institution: 'European Commission / EIF',
    country: 'EU',
    flag: '🇪🇺',
    type: 'eu_fund',
    audience: ['startup', 'sme', 'individual'],
    description:
      'The EaSI (Employment and Social Innovation) programme supports social enterprises and microfinance for vulnerable groups across all EU member states including Estonia, Latvia, Lithuania, Denmark, and Finland.',
    maxAmount: 500000,
    currency: 'EUR',
    rateMin: 2.0,
    rateMax: 6.0,
    features: [
      'Microloans up to €25,000',
      'Social enterprise loans up to €500K',
      'Vulnerable group focus',
      'Below-market rates',
      'Via local microfinance institutions',
    ],
    requirements: [
      'Social enterprise or microenterprise',
      'Job creation / social impact',
      'Cannot access regular bank credit',
    ],
    link: 'https://ec.europa.eu/social/main.jsp?catId=1081',
    tags: ['EU', 'social', 'microloan', 'inclusive'],
  },

  // ============================================================
  // 🏠 GOVERNMENT HOUSING PROGRAMS
  // ============================================================
  {
    id: 'is-hms-housing',
    name: 'HMS Housing Fund Loan',
    institution: 'Húsnæðis- og mannvirkjastofnun (HMS)',
    country: 'IS',
    flag: '🇮🇸',
    type: 'government_loan',
    audience: ['individual'],
    description:
      'HMS is the Icelandic Housing and Construction Authority. It provides subsidized housing loans for individuals, particularly first-time buyers and lower-income households, with government-backed rates.',
    maxAmount: 100000000,
    currency: 'ISK',
    rateMin: 4.5,
    rateMax: 7.0,
    termMaxMonths: 360,
    features: [
      'Government-subsidized rates',
      'First-time buyer priority',
      'CPI-indexed and non-indexed options',
      'Up to 90% LTV for first home',
      'Nationwide availability',
    ],
    requirements: [
      'Icelandic resident',
      'Property in Iceland',
      'Income-based assessment',
    ],
    link: 'https://www.hms.is/en',
    tags: ['housing', 'first-time buyer', 'iceland', 'government'],
  },
  {
    id: 'se-sbab-housing',
    name: 'SBAB First-Time Buyer Loan',
    institution: 'SBAB Bank (Government-Owned)',
    country: 'SE',
    flag: '🇸🇪',
    type: 'government_loan',
    audience: ['individual'],
    description:
      "SBAB is Sweden's government-owned mortgage bank with a mission to promote competition in the housing finance market. Competitive mortgage rates with a strong sustainability profile.",
    maxAmount: 15000000,
    currency: 'SEK',
    rateMin: 3.4,
    rateMax: 5.5,
    termMaxMonths: 360,
    features: [
      'Government-backed stability',
      'Competitive mortgage rates',
      'Green mortgage discount',
      'First-time buyer guidance',
      'Transparent pricing',
    ],
    requirements: [
      'Swedish resident',
      'Property in Sweden',
      'Income assessment',
    ],
    link: 'https://www.sbab.se/privatperson/bolan.html',
    tags: ['mortgage', 'sweden', 'government', 'first-time buyer'],
  },
];

export const PROGRAM_TYPE_LABELS: Record<string, string> = {
  government_loan: 'Government Loan',
  grant: 'Grant / Non-Repayable',
  guarantee: 'Loan Guarantee',
  e_residency: 'e-Residency / Digital Banking',
  digital_nomad_visa: 'Digital Nomad Visa',
  startup_visa: 'Startup / Freelancer Visa',
  eu_fund: 'EU Fund',
  startup_loan: 'Startup Loan',
  microloan: 'Micro Loan',
  innovation_fund: 'Innovation Fund',
  export_credit: 'Export Credit',
};

export const PROGRAM_TYPE_ICONS: Record<string, string> = {
  government_loan: '🏦',
  grant: '🎁',
  guarantee: '🛡️',
  e_residency: '🪪',
  digital_nomad_visa: '🌐',
  startup_visa: '✈️',
  eu_fund: '🇪🇺',
  startup_loan: '🚀',
  microloan: '💰',
  innovation_fund: '💡',
  export_credit: '📦',
};

export const AUDIENCE_LABELS: Record<string, string> = {
  digital_nomad: '🌐 Digital Nomad',
  e_resident: '🪪 e-Resident',
  startup: '🚀 Startup',
  sme: '🏢 SME',
  individual: '👤 Individual',
  corporate: '🏛️ Corporate',
  innovator: '💡 Innovator',
  exporter: '📦 Exporter',
  freelancer: '💻 Freelancer',
};
